version: '3.8'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: example

  web:
    build: ./web
    volumes:
      - ./web:/code
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      REPO_URL: https://github.com/tavoli-rgb/boxen.git

volumes:
  db_data: